# A program that demonstrates the breath checking method

import turtle
wn=turtle.Screen()
t=turtle.getturtle()
wn.title("OXIMETER")
wn.bgpic("lungs 2.gif")
turtle.setup(600,600)
wn.bgcolor("pink")

t.penup()
t.setposition(-100,290)
t.pendown()
t.color("DarkOrchid")
t.write("Breath Test", font=("Vegan",30,"italic"))
t.penup()
t.setposition(-100,290)
t.pendown()
t.pensize(7)
t.color("deep pink")
t.setposition(100,290)

t.shape('arrow')
t.penup()
t.setposition(-300,200)
t.pendown()
t.color('deep pink')
turtle.write("LET'S CHECK OUR BREATHING CONDITION....", font=("verdana",25,"italic"))
turtle.delay(100)
turtle.hideturtle()

t.pensize(4)
t.color('brown')
t.penup()
t.setposition(-400,120)
t.pendown()
turtle.write("** BREATH IN **", font=("Verdana",15,"normal"))
t.penup()
t.setposition(-90,120)
t.pendown()
turtle.write(" ** HOLD UR BREATH ** ", font=("Verdana",15,"normal"))
t.penup()
t.setposition(250,120)
t.pendown()
turtle.write("** BREATH OUT **", font=("Verdana",15,"normal"))
t.speed('normal')

t.speed(10)
t.penup()
t.setposition(-400,-120)
t.pendown()
turtle.write("REMARKS : ", font=("verdana",20,"italic"))

t.shape("circle")
t.pensize(10)
t.penup()
t.setposition(-400,100)
t.pendown()

t.speed(1)
turtle.delay(50)
t.color('blue')
t.setposition(-250,100)
t.speed(1)
turtle.delay(200)
t.color('red')
t.setposition(250,100)
t.speed(1)
turtle.delay(50)
t.color('blue')
t.setposition(400,100)

t.speed(10)
t.penup()
t.goto(-200,-160)
t.pensize(2)
t.color("deep pink")
t.pendown()
t.color("green")
t.write("** IF YOU ARE ABLE TO DO IT THEN U ARE FREE FROM CORONA **", font=("Verdana",15,"normal"))

t.penup()
t.setposition(-200,-200)
t.pendown()
t.color("red")
t.write("** ELSE MOVE FOR FURTHER PRECAUTIONS AND CHECKUPS **", font=("Verdana",15,"normal"))

wn.bgcolor("black")
t.pensize(7)
t.color("gold")

t.penup()
t.goto(-500,0)
t.pendown()
t.pensize(1)

for i in range(9):
	t.forward(25)
	t.left(165)
	t.forward(25)
t.penup()
t.goto(-450,-10)
t.pendown()

turtle.write("STAY HOME ...", font=("Verdana",25,"italic"))
	
t.penup()
t.goto(200,-10)
t.pendown()

turtle.write("STAY SAFE ... :-)", font=("Verdana",25,"italic"))

t.penup()
t.goto(550,0)
t.pendown()
for i in range(9):
	t.forward(25)
	t.left(165)
	t.forward(25)
turtle.hideturtle()
